/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import javax.swing.JOptionPane;

/**
 *
 * @author Nay Ale
 */
public class Contenedor_MDI extends javax.swing.JFrame {

    /**
     * Creates new form Contenedor_MDI
     */
    public Contenedor_MDI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuManAlum = new javax.swing.JMenuItem();
        jMenuManMaes = new javax.swing.JMenuItem();
        jMenuManFacul = new javax.swing.JMenuItem();
        jMenuManCarre = new javax.swing.JMenuItem();
        jMenuManCursos = new javax.swing.JMenuItem();
        jMenuManSecc = new javax.swing.JMenuItem();
        jMenuManSedes = new javax.swing.JMenuItem();
        jMenuManAulas = new javax.swing.JMenuItem();
        jMenuManJor = new javax.swing.JMenuItem();
        jMenuAsigCurAlum = new javax.swing.JMenu();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuAsigCurMaes = new javax.swing.JMenuItem();
        jMenuAsigNotas = new javax.swing.JMenuItem();
        jMenuRecepActasR = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        jMenu10 = new javax.swing.JMenu();
        jMenu11 = new javax.swing.JMenu();
        jMenuSalida = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jDesktopPane1.setBackground(new java.awt.Color(0, 0, 102));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 682, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        jMenu3.setText("Abrir");

        jMenuItem2.setText("Usuario");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuBar2.add(jMenu3);

        jMenu4.setText("Catalogos");

        jMenuManAlum.setText("Mantenimiento Alumno");
        jMenu4.add(jMenuManAlum);

        jMenuManMaes.setText("Mantenimiento Maestros");
        jMenu4.add(jMenuManMaes);

        jMenuManFacul.setText("Mantenimiento Facultades");
        jMenu4.add(jMenuManFacul);

        jMenuManCarre.setText("Mantenimiento Carreras");
        jMenu4.add(jMenuManCarre);

        jMenuManCursos.setText("Mantenimiento Cursos");
        jMenu4.add(jMenuManCursos);

        jMenuManSecc.setText("Mantenimiento Secciones");
        jMenu4.add(jMenuManSecc);

        jMenuManSedes.setText("Mantenimiento Sedes");
        jMenu4.add(jMenuManSedes);

        jMenuManAulas.setText("Mantenimiento Aulas");
        jMenu4.add(jMenuManAulas);

        jMenuManJor.setText("Mantenimiento Jornadas");
        jMenu4.add(jMenuManJor);

        jMenuBar2.add(jMenu4);

        jMenuAsigCurAlum.setText("Procesos");

        jMenuItem11.setText("Asignacion Cursos Alumnos");
        jMenuAsigCurAlum.add(jMenuItem11);

        jMenuAsigCurMaes.setText("Asignacion Cursos Maestros");
        jMenuAsigCurAlum.add(jMenuAsigCurMaes);

        jMenuAsigNotas.setText("Ingreso de Notas");
        jMenuAsigCurAlum.add(jMenuAsigNotas);

        jMenuRecepActasR.setText("Recepción de Actas en Registro");
        jMenuAsigCurAlum.add(jMenuRecepActasR);

        jMenuBar2.add(jMenuAsigCurAlum);

        jMenu9.setText("Informes");
        jMenuBar2.add(jMenu9);

        jMenu10.setText("Herramientas");
        jMenuBar2.add(jMenu10);

        jMenu11.setText("Ayuda");

        jMenuSalida.setText("Salir ");
        jMenuSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSalidaActionPerformed(evt);
            }
        });
        jMenu11.add(jMenuSalida);

        jMenuBar2.add(jMenu11);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSalidaActionPerformed
        /*===== OPERACIÓN CERRAR SESIÓN ====
          Variable entera respuesta_cs*/

        int respuesta_cs = JOptionPane.showConfirmDialog(this, "¿Desea Cerrar Sesión?", "Cerrar Sesión", JOptionPane.YES_NO_OPTION);

        if (respuesta_cs == 0) {
            this.dispose();
        }
    }//GEN-LAST:event_jMenuSalidaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Contenedor_MDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Contenedor_MDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Contenedor_MDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Contenedor_MDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Contenedor_MDI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenu jMenuAsigCurAlum;
    private javax.swing.JMenuItem jMenuAsigCurMaes;
    private javax.swing.JMenuItem jMenuAsigNotas;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuManAlum;
    private javax.swing.JMenuItem jMenuManAulas;
    private javax.swing.JMenuItem jMenuManCarre;
    private javax.swing.JMenuItem jMenuManCursos;
    private javax.swing.JMenuItem jMenuManFacul;
    private javax.swing.JMenuItem jMenuManJor;
    private javax.swing.JMenuItem jMenuManMaes;
    private javax.swing.JMenuItem jMenuManSecc;
    private javax.swing.JMenuItem jMenuManSedes;
    private javax.swing.JMenuItem jMenuRecepActasR;
    private javax.swing.JMenuItem jMenuSalida;
    // End of variables declaration//GEN-END:variables
}
